name: "davidkhala/setup-odbc"
description: 'Install ODBC driver in runner'

branding:
  icon: 'database'
  color: 'blue'
inputs:
  version:
    description: 'ODBC version to install'
    required: false
    default: "18"
runs:
  using: "composite"
  steps:
  - if: runner.os == 'Linux'
    run: curl -fsSL https://raw.githubusercontent.com/davidkhala/ubuntu-utils/refs/heads/master/database/mssql/install.sh | bash -s odbc ${{ inputs.version }}
    shell: bash
  - if: runner.os == 'macOS'
    run: curl -fsSL https://raw.githubusercontent.com/davidkhala/mac-utils/refs/heads/master/database/mssql/install.sh | bash -s odbc ${{ inputs.version }}
    shell: bash
  - if: runner.os == 'Windows'
    run: |
      iex (irm https://raw.githubusercontent.com/davidkhala/windows-utils/refs/heads/master/database/mssql.ps1)
      Install-ODBC -Version "${{ inputs.version }}"
    shell: powershell